name             'zabbix-server'
maintainer       'Express 42 LLC'
maintainer_email 'cookbooks@express42.com'
license          'Apache 2.0'
description      'Installs/Configures zabbix-server'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
depends          'lvm', '>= 0.8.6'
depends          'partition', '>= 0.1.0'
depends          'nginx', '>= 2.2.0'
version          '0.1.0'
